/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}",
    "./node_modules/flowbite/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        display: [
          '"Bricolage Grotesque"',
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        sans: [
          '"Bricolage Grotesque"',
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        mono: [
          '"JetBrains Mono"',
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Consolas",
          "monospace",
        ],
      },
      colors: {
        ink: "rgb(var(--ink) / <alpha-value>)",
        "ink-muted": "rgb(var(--ink-muted) / <alpha-value>)",
        paper: "rgb(var(--paper) / <alpha-value>)",
        "paper-raised": "rgb(var(--paper-raised) / <alpha-value>)",
        accent: "rgb(var(--accent) / <alpha-value>)",
        hairline: "rgb(var(--ink) / 0.12)",
      },
      letterSpacing: {
        tight2: "-0.035em",
        label: "0.14em",
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            "--tw-prose-body": "rgb(var(--ink))",
            "--tw-prose-headings": "rgb(var(--ink))",
            "--tw-prose-lead": "rgb(var(--ink-muted))",
            "--tw-prose-links": "rgb(var(--accent))",
            "--tw-prose-bold": "rgb(var(--ink))",
            "--tw-prose-counters": "rgb(var(--ink-muted))",
            "--tw-prose-bullets": "rgb(var(--ink-muted))",
            "--tw-prose-hr": "rgb(var(--ink) / 0.12)",
            "--tw-prose-quotes": "rgb(var(--ink))",
            "--tw-prose-quote-borders": "rgb(var(--accent))",
            "--tw-prose-captions": "rgb(var(--ink-muted))",
            "--tw-prose-code": "rgb(var(--ink))",
            "--tw-prose-pre-code": "rgb(var(--ink))",
            "--tw-prose-pre-bg": "rgb(var(--paper-raised))",
            "--tw-prose-th-borders": "rgb(var(--ink) / 0.2)",
            "--tw-prose-td-borders": "rgb(var(--ink) / 0.12)",
            "--tw-prose-invert-body": "rgb(var(--ink))",
            "--tw-prose-invert-headings": "rgb(var(--ink))",
            "--tw-prose-invert-links": "rgb(var(--accent))",
            "--tw-prose-invert-bold": "rgb(var(--ink))",
            "--tw-prose-invert-hr": "rgb(var(--ink) / 0.12)",
            "--tw-prose-invert-quotes": "rgb(var(--ink))",
            "--tw-prose-invert-quote-borders": "rgb(var(--accent))",
            "--tw-prose-invert-code": "rgb(var(--ink))",
            "--tw-prose-invert-pre-code": "rgb(var(--ink))",
            "--tw-prose-invert-pre-bg": "rgb(var(--paper-raised))",
            fontFamily: theme("fontFamily.sans").join(", "),
            fontSize: "1.0625rem",
            lineHeight: "1.7",
            a: {
              textDecoration: "underline",
              textUnderlineOffset: "3px",
              textDecorationThickness: "1px",
              fontWeight: "500",
              transition: "color 150ms ease",
              "&:hover": { color: "rgb(var(--accent))" },
            },
            h1: {
              fontFamily: theme("fontFamily.display").join(", "),
              letterSpacing: "-0.035em",
              fontWeight: "700",
            },
            h2: {
              fontFamily: theme("fontFamily.display").join(", "),
              letterSpacing: "-0.035em",
              fontWeight: "600",
              marginTop: "2.5em",
            },
            h3: {
              fontFamily: theme("fontFamily.display").join(", "),
              letterSpacing: "-0.025em",
              fontWeight: "600",
            },
            code: {
              fontFamily: theme("fontFamily.mono").join(", "),
              fontSize: "0.92em",
              padding: "0.15em 0.35em",
              backgroundColor: "rgb(var(--paper-raised))",
              borderRadius: "0",
              border: "1px solid rgb(var(--ink) / 0.08)",
              fontWeight: "500",
            },
            "code::before": { content: '""' },
            "code::after": { content: '""' },
            pre: {
              fontFamily: theme("fontFamily.mono").join(", "),
              fontSize: "0.875rem",
              border: "1px solid rgb(var(--ink) / 0.12)",
              borderRadius: "0",
              backgroundColor: "rgb(var(--paper-raised))",
            },
            "pre code": {
              border: "none",
              padding: "0",
              backgroundColor: "transparent",
              fontWeight: "400",
            },
            blockquote: {
              fontStyle: "normal",
              borderLeftWidth: "3px",
              paddingLeft: "1.25em",
            },
            "blockquote p:first-of-type::before": { content: '""' },
            "blockquote p:last-of-type::after": { content: '""' },
            hr: {
              borderTopWidth: "1px",
              marginTop: "3em",
              marginBottom: "3em",
            },
            img: { borderRadius: "0" },
            figure: { marginTop: "2em", marginBottom: "2em" },
            figcaption: {
              fontSize: "0.85rem",
              textAlign: "center",
            },
          },
        },
      }),
    },
  },
  plugins: [
    require("flowbite/plugin"),
    require("@tailwindcss/typography"),
  ],
};
